[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && sed -i \"s|https\\:\\/\\/example\\.com\\/|${URL}\\/|g\" config.yaml && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.63.2"
  HUGO_THEME = "repo"