theme: someparts-hugo
baseURL: https://example.com/
copyright: CC BY-NC-SA 4.0 international
enableGitInfo: true
disableKinds:
- taxonomy
- taxonomyTerm
- categories

frontmatter:
  lastmod: 
    - date
    - :git

params:
  author: Sandro Leuchter
  description: color, colour, palette, someparts-hugo
  title: My Palette
  lang: en
  icon: <i class="fa fa-paint-brush" aria-hidden="true"></i>
  lastmod: last modified
  googleAnalytics: UA-XXXXX
  cookieconsent:
    message: We use cookies and Google Analytics to make this website as interesting as possible for you. Do you agree to this? (You can revoke this decision at any time)
    denyLabel: Deny
    allowLabel: Allow
    policy:
      linktext: privacy policy
      url: privacy/
  dropdown: 
    - entry1:
      url: index.html
      linktext: Overview
    - divider2:
    - entry3:
      url: https://dama.io/
      linktext: External Colorist
    - divider4: 
    - entry6:
      url: imprint/
      linktext: Imprint
    - entry7:
      url: privacy/
      linktext: Privacy Policy
    - divider8:
    - entry9:
      url: index.xml
      linktext: RSS
